---
version: 2
updates:
- package-ecosystem: "github-actions"
  directories:
  - /
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
- package-ecosystem: "helm"
  enable-beta-ecosystems: true
  directories:
  - /charts/common
  - /examples/common/grpc-app
  - /examples/common/multi-container
  - /examples/common/multi-deploy
  - /examples/common/simple-app
  - /examples/common/typical-backend
  - /examples/common/typical-frontend
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
