{{- /* Rules */}}
{{- $env := .Values.env | required ".Values.common.env is required." -}}
{{- $releaseName := include "name" . -}}
{{- $minReplicas := .Values.deployment.minReplicas }}
{{- $forceReplicas := .Values.deployment.forceReplicas }}
{{- $maxReplicas := .Values.deployment.maxReplicas }}
{{- $hpa := .Values.hpa | default dict }}
{{- $cpuUtilization := .Values.deployment.cpuUtilization | default 70 }}

{{- if eq (include "hpa.enabled" (dict "forceReplicas" $forceReplicas)) "true"  }}
  {{- /* Rules */}}
  {{- if (eq 1 (int $maxReplicas)) }}
    {{- required ".Values.common.deployment.maxReplicas must be more than 1." .Values.error -}}
  {{- else }}

{{- /* YAML Spec */}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $releaseName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . |trim| nindent 4 }}
  annotations:
    {{- include "annotations" . |trim| nindent 4 }}
spec:
  {{- if ((.Values.hpa).spec) }}
  {{ toYaml .Values.hpa.spec | nindent 2 }}
  {{- else }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $cpuUtilization }}
  {{- range ((.Values.hpa).metrics) }}
  - {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if not ((.Values.deployment).startupCPUBoost).enabled }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ ((.Values.hpa).stabilizationWindowSeconds) | default 120 }}
  {{- end }}
  maxReplicas: {{ $maxReplicas | default 10 }}
  minReplicas: {{ include "hpa.minReplicas" (dict "env" $env "replicas" $minReplicas) }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $releaseName }}
{{- end }}
{{- end }}
