{{- /* Rules */}}
{{- $chart := . -}}
{{- $releaseNamespace := .Release.Namespace -}}

{{- /* YAML Spec */}}
{{- range $secretName, $secretValues := .Values.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  namespace: {{ $releaseNamespace }}
  labels:
    {{- include "labels" $chart | indent 4 }}
spec:
  data:
  {{- range $secretValues }}
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ . }}
      version: latest
    secretKey: {{ . }}
  {{- end }}
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $.Values.app }}
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: {{ $secretName }}

# Must manually print newlines for unittest, do not remove
{{ print "\n---\n" }}

{{- end }}
