{{- /* Rules */}}
{{- $chart := . -}}
{{- $releaseNamespace := .Release.Namespace -}}
{{- $releaseName := include "name" . -}}
{{- $storeName := .Values.secrets.secretStoreName | default $.Values.app -}} 
{{- $secrets := unset .Values.secrets "secretStoreName" -}}
{{- /* YAML Spec */}}
{{- range $secretName, $secretValues := $secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $releaseName }}-{{ $secretName }}
  namespace: {{ $releaseNamespace }}
  labels:
    {{- include "labels" $chart |trim| nindent 4 }}
  annotations:
    timestamp: {{ now | date "2006-01-02T15:04:05" }}
spec:
  data:
  {{- range $secretValues }}
  # if contains - stop with error
  {{- if contains "-" . }}
  {{- fail "SecretNames cannot contain dashes" }}
  {{- end }}
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ . }}
      version: latest
    secretKey: {{ . }}
  {{- end }}
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $storeName }}
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: {{ $releaseName }}-{{ $secretName }}

# Must manually print newlines for unittest, do not remove
{{ print "\n---\n" }}

{{- end }}
