{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels" . | indent 4 }}
  name: {{ .Release.Name }}
  {{- if .Values.grpc }}
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- if .Values.service.ports }}
  {{- toYaml .Values.service.ports | nindent 4 }}
  {{- else }}
  - name: http
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
{{- end }}
