{{- $releaseName := include "name" . -}}
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels" . | indent 4 }}
  name: {{ $releaseName }}
  annotations:
  {{- if .Values.grpc }}
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  {{- end }}
  {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- if .Values.service.ports }}
  {{- toYaml .Values.service.ports | nindent 4 }}
  {{- else }}
  - name: http
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  {{- end }}
  selector:
    app: {{ $releaseName }}
  type: ClusterIP
{{- end }}
