multi-1:
  env: dev
  ingress:
    trafficType: public
    host: multi1.dev.entur.io
  configmap:
    data:
      ENVIRONMENT: dev
multi-2:
  env: dev
  ingress:
    trafficType: public
    host: multi2.dev.entur.io
  configmap:
    data:
      ENVIRONMENT: dev
