version: '2.1'
orbs:
  helm: circleci/helm@3.0.0
jobs:
  test:
    docker:
      - image: cimg/base:2023.09
    working_directory: ~/docs/examples/common
    steps:
      - checkout
      - helm/install-helm-client
      - run: make test
workflows:
  test:
    jobs:
      - test
