app: my-app
shortname: myapp
team: plattform
env: dev

ingress:
  enabled: false

service:
  enabled: false

cron:
  enabled: true
  schedule: "* * * * *"

deployment:
  enabled: false

container:
  name: my-app
  image: nginx:stable-alpine

secrets:
  external-secret:
    - CRON_SECRET

labels:
  customLogRetention: "enabled"