common:
  app: typical-frontend
  shortname: typfro
  team: example
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 9000
  deployment:
    prometheus:
      enabled: true
    replicas: 2
  container:
    image: <+artifacts.primary.image>
    cpu: 0.3
    memory: 512
  configmap:
    enabled: true
    data:
      TZx: "Europe/Oslo"
  secrets:
    auth-credentials: # k8s secret name "typical-frontend-auth-credentials"
      - MNG_AUTH0_INT_CLIENT_ID
      - MNG_AUTH0_INT_CLIENT_SECRET
