common:
  app: typical-backend
  shortname: typbak
  team: team-example
  ingress:
    enabled: true
    trafficType: api
  service:
    internalPort: 9000
  deployment:
    prometheus:
      enabled: false  # set this to true only when you have setup a metrics endpoint
    replicas: 2
  container:
    image: <+artifacts.primary.image>
    cpu: 0.3 # Adjust this to your application needs
    memory: 512 # Adjust this to your application needs
  postgres: # sets up a postgres proxy so you can connect to your postgresql instance via localhost on the pod
    enabled: true
    cpu: 0.1
    memory: 32
  secrets:
    auth-credentials: # k8s secret name "typical-backend-auth-credentials"
      - MNG_AUTH0_INT_CLIENT_ID
      - MNG_AUTH0_INT_CLIENT_SECRET
