common:
  app: typical-backend
  shortname: typbak
  team: example
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 9000
  container:
    image: ${artifact.metadata.image}
    cpu: 0.3
    memory: 128
    replicas: 2
    env:
      - name: YOU_SHOULD_PROBABLY_USE_CONFIGMAP
        value: yes_you_should
    envFrom:
      - secretRef:
          name: my-secret-thing
    prometheus:
      enabled: true
    probes:
      liveness:
        path: "/alive"
  configmap:
    enabled: true
    data:
      TZx: "Europe/Oslo"
      LOG_LEVEL: ${serviceVariable.log_level} 
  postgres:
    enabled: true
    cpu: 0.1
    memory: 32
