common:
  env: prd
  ingress:
    host:
      typical-backend.entur.org
  container:
    replicas: 2
    maxReplicas: 6
  configmap:
    enabled: true
    toEnv: true
    data:
      ENVIRONMENT: prod
