name: Test Hello Worldyes

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello
        uses: entur/gha-flows/.github/workflows/hello-world
