name: Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review

env:
  CHART_NAME: common

jobs:
  helm-unittest:
    name: helm unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.1

      - name: Helm Unit Test
        run: |
          helm plugin install https://github.com/vbehar/helm3-unittest
          helm unittest charts/common

  helm-install:
    name: helm install (KIND)
    runs-on: ubuntu-latest
    needs: helm-unittest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@dae259e86a35ff09145c0805e2d7dd3f7207064a # v2.2.1, ct=v3.5.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Lint Helm
        run: ct lint --config config.yaml --check-version-increment false --charts charts/${{ env.CHART_NAME }} --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@d08cf6ff1575077dee99962540d77ce91c62387d
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --debug --charts charts/${{ env.CHART_NAME }}
